# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs           = -Xmx3G
org.gradle.daemon            = false

minecraft_version            = 1.21.1
minecraft_version_range      = [1.21.1]
neo_version                  = 21.1.248
neo_version_range            = [21.1.248,)
loader_version_range         = [4,)

create_version               = 6.0.10-280
ponder_version               = 1.0.82
flywheel_version             = 1.0.6
registrate_version           = MC1.21-1.3.0+67

mapping_channel              = official
mapping_version              = 1.21.1

parchment_minecraft_version  = 1.21.1
parchment_mappings_version   = 2024.11.17

mod_id                       = createliquidfuel
mod_name                     = Create Liquid Fuel
mod_license                  = MIT NON-AI
mod_version                  = 3.0.0-1.21.1
mod_group_id                 = com.forsteri.createliquidfuel
mod_authors                  = Wolfieboy09
mod_credits                  = "Forsteri"

mod_description              = "Input liquid into blaze burner with pumps & pipes"