modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT NON-AI"
issueTrackerURL="https://github.com/wolfieboy09/CreateLiquidFuelUpdate/issues"
[[mods]]
    modId="createliquidfuel"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.createliquidfuel]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.createliquidfuel]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.createliquidfuel]]
    modId="create"
    type="required"
    versionRange="[6.0.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createliquidfuel]]
    modId="kubejs"
    type="optional"
    versionRange="[${kubejs_version},)"
    ordering="NONE"
    side="SERVER"

[[dependencies.createliquidfuel]]
    modId="jei"
    type="optional"
    versionRange="[${jei_version},)"
    ordering="NONE"
    side="BOTH"


[[mixins]]
config = "createliquidfuel.mixins.json"