modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="createliquidfuel"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.createliquidfuel]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.createliquidfuel]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.createliquidfuel]]
    modId="create"
    mandatory=true
    versionRange="[6.0.10,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config = "createliquidfuel.mixins.json"